python initial.py 
2023-07-04 17:09:58.681137: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-04 17:09:58.684939: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/christy/Documents/Myself/Academia/PG docs/Projects/FR-Robot/ROBO-env/lib/python3.10/site-packages/cv2/../../lib64:
2023-07-04 17:09:58.684965: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "/home/christy/Documents/Myself/Academia/PG docs/Projects/FR-Robot/ROBO-Project/Face_recognition/multi-facerecognition/initial.py", line 132, in <module>
    main1()
  File "/home/christy/Documents/Myself/Academia/PG docs/Projects/FR-Robot/ROBO-Project/Face_recognition/multi-facerecognition/initial.py", line 109, in main1
    face_recognition_results = identify_faces(known_face_embeddings, known_face_names, frame)
  File "/home/christy/Documents/Myself/Academia/PG docs/Projects/FR-Robot/ROBO-Project/Face_recognition/multi-facerecognition/initial.py", line 64, in identify_faces
    for face_crop, start_x, start_y in zip(face_crops, start_points_x, start_points_y):
TypeError: 'int' object is not iterable (ROBO-env) 
christy@christy-VivoBook-ASUSLap
